
import cdsapi
import calendar
import datetime
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import zipfile
import logging
from pathlib import Path
import os
import re
from c3s_atlas.utils import (
    extract_zip_and_delete
)
from utils import build_output_path, is_valid_netcdf

def download_single_file(catalogue_id: str, catalogue_entry: dict, output_path: Path) -> Path:
    """
    Download a file from a given catalogue ID with the given parameters.
    This method retrieves the file from the CDS API, saves it in a temporary
    directory, and returns the `Path` object pointing to the downloaded file.
    Parameters
    ----------
    catalogue_id : str
        A string containing the CDS catalogue id. For instance: projections-cmip6.
    catalogue_entry: dict
        A dictionary containing the fields of the requested data.
    output_path: Path
        Path associated with the request params.
    Returns
    -------
    output_path: Path
        A `Path` object pointing to the downloaded file.
    Raises
    ------
    Exception
        If the download request failed.
    """
    start_time = datetime.datetime.now()
    c = cdsapi.Client(timeout=500, quiet=True)
    logging.info(f"Downloading the data from {catalogue_id} with parameters {catalogue_entry}")
    r = c.retrieve(catalogue_id, catalogue_entry)
    r.download(output_path)
    end_time = datetime.datetime.now()
    final_time = end_time - start_time
    logging.info(f"Duration of the process to download data: {final_time}")
    logging.info(f"Saving to {output_path}")
    return output_path





def handle_special_zip(zip_path, delete_zip=False, request_frequency="yearly", extracted_frequency="daily"):
    """
    Extract zip files and keep the files generated by the zip as-is.
    Does NOT rename extracted .nc files to match the zip name.
    Non-.nc files extracted alongside will be removed.

    Parameters
    ----------
    zip_path : pathlib.Path or str
        Path to the downloaded zip file
    delete_zip : bool
        If True, delete the original zip after extraction
    request_frequency : str, optional
        Frequency of the requests ("yearly", "monthly", "daily").
    """

    zip_path = Path(zip_path)
    zip_directory = zip_path.parent
    if request_frequency == "monthly":
        # detects YEAR and MONTH in ZIP name (YYYYMM)
        zip_date_pattern = re.compile(r'(\d{6})')
    elif request_frequency == "yearly":
        # detects YEAR in ZIP name (4 digits)
        zip_date_pattern = re.compile(r'(\d{4})')
    else:
        raise ValueError(f"Unsupported request frequency: {request_frequency} when extracting zip file {zip_path}")

    # detects full timestamp in nc file
    if extracted_frequency == "daily":
        date_digits = 8
    elif extracted_frequency == "monthly":
        date_digits = 6
    nc_date_pattern = re.compile(rf'(\d{{{date_digits}}})(?=.*\.nc$)')
    if not zipfile.is_zipfile(zip_path):
        logging.info(f"File {zip_path} is not a zip archive; nothing to extract")
        return

    logging.info(f"Processing: {zip_path}")

    # base name without extension
    base_name = os.path.basename(zip_path).replace(".zip", "")
    date_zip = zip_date_pattern.search(base_name)

    if not date_zip:
        logging.info(f"Skipping (no year in zip): {zip_path}")
        return
    original_date = date_zip.group(1)

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        for nc_file in zip_ref.namelist():
            if not nc_file.endswith(".nc"):
                continue

            # ---- extract real daily date ----
            date_nc = nc_date_pattern.search(nc_file)
            if not date_nc:
                logging.info(f"Skipping (no date): {nc_file}")
                continue

            new_date = date_nc.group(1)

            # ---- replace original date in basename ----
            new_basename = base_name.replace(original_date, new_date)

            new_name = f"{new_basename}.nc"
            new_path = os.path.join(zip_directory, new_name)

            with zip_ref.open(nc_file) as src, open(new_path, "wb") as dst:
                dst.write(src.read())

            logging.info(f"Saved: {new_name}")

    if delete_zip:
        try:
            zip_path.unlink()
        except Exception as e:
            logging.warning(f"Could not delete zip file {zip_path}: {e}")



def file_exists_and_valid(path_file, multinetcdf_zip):
    """
    Check whether the expected output file already exists and is valid.

    Returns
    -------
    bool
        True if file exists and is valid, False otherwise.
    """

    path_file = Path(str(path_file))

    if multinetcdf_zip:
        if path_file.exists():
            logging.info(f"{path_file} already exists and is valid, skipping")
            return True
        else:
            logging.warning(f"{path_file} does not exist, redownloading")
            return False

    nc_path = Path(str(path_file).replace("zip", "nc"))

    if nc_path.exists() :
        if is_valid_netcdf(nc_path):
            logging.info(f"{path_file} already exists and is valid, skipping")
            return True
        else:
            logging.warning(f"{path_file} exists but is corrupt, redownloading")
            return False
    else:
        logging.info(f"{path_file} does not exist, scheduling download")
        return False

def zip_extractor(path_file, multinetcdf_zip, request_frequency, extracted_frequency):
    """
    Check for an existing valid NetCDF file corresponding to path_file, and if missing or invalid,
    schedule download and/or post-processing tasks on the provided executor.

    Parameters
    ----------
    path_file : pathlib.Path or str
        Path to the target file. If a .zip path is provided, the function uses a corresponding
        .nc path (by replacing 'zip' with 'nc') to check for an already extracted NetCDF file.

    multinetcdf_zip : bool or None, optional
        Controls how .zip files are handled:
    """
    # evaluate the variable settings_file to determine how to handle the zip file
    if multinetcdf_zip:
        handle_special_zip(path_file, delete_zip=False, request_frequency=request_frequency, extracted_frequency=extracted_frequency)
    else:
        extract_zip_and_delete(path_file)


        

def process_single_request(
    row,
    dataset,
    dest_dir,
    create_request_func,
    get_output_filename_func,
    args,
    is_multinetcdf_zip,
    request_frequency,
    extracted_frequency
):
    request = create_request_func(row, *args)
    file = get_output_filename_func(row, dataset, *args)
    path_file = dest_dir / file

    valid_file = file_exists_and_valid(path_file, is_multinetcdf_zip)

    #if valid_file:
    #    return

    # download
    #download_single_file(row["dataset"], request, path_file)

    # extract (if needed)
    if path_file.suffix == ".zip":
        zip_extractor(path_file, is_multinetcdf_zip, request_frequency, extracted_frequency)


def download_files(dataset, variables_file_path, create_request_func, get_output_filename_func, request_frequency="yearly", extracted_frequency="daily"):
    """
    Download files for the specified variables and years.

    Parameters
    ----------
    dataset : str
        The dataset name.
    variables_file_path : str
        Path to the CSV file containing the variables and other parameters.
    create_request_func : function
        Function to create the request dictionary.
    get_output_filename_func : function
        Function to get the output filename.
    request_frequency : str, optional
        Frequency of the requests ("yearly", "monthly", "daily").
    """
    df_parameters = pd.read_csv(variables_file_path)
    for index, row in df_parameters.iterrows():
        if row["product_type"] != "raw":
            continue

        dest_dir = build_output_path(
            row["output_path"], 
            dataset, 
            row["product_type"],
            row["temporal_resolution"],
            row["interpolation"],
            row["filename_variable"]
        )
        dest_dir.mkdir(parents=True, exist_ok=True)

        year_list = list(range(row["cds_years_start"], row["cds_years_end"] + 1))

        if "is_multinetcdf_zip" in df_parameters.columns:
            val = row["is_multinetcdf_zip"]
            is_multinetcdf_zip = None if pd.isna(val) else bool(val)
        else:
            is_multinetcdf_zip = None

        month_list = [f"{month:02d}" for month in range(1, 13)]
        logging.info(f"Processing variable {row['filename_variable']} for dataset {dataset} with years {year_list[0]}-{year_list[-1]} and request frequency {request_frequency}")
        with ThreadPoolExecutor(max_workers=1) as executor:
            futures = []
            
            def submit(*args):
                futures.append(
                    executor.submit(
                        process_single_request,
                        row,
                        dataset,
                        dest_dir,
                        create_request_func,
                        get_output_filename_func,
                        args,
                        is_multinetcdf_zip,
                        request_frequency,
                        extracted_frequency
                    )
                )
            if request_frequency == "monthly":
                for year in year_list:
                    for month in month_list:
                        submit(year, month)

            elif request_frequency == "daily":
                for year in year_list:
                    for month in month_list:
                        num_days = calendar.monthrange(year, int(month))[1]
                        for day in range(1, num_days + 1):
                            submit(year, month, f"{day:02d}")

            elif request_frequency == "yearly":
                for year in year_list:
                    submit(year)

            else:
                submit()

            for future in futures:
                try:
                    future.result()
                except Exception as e:
                    logging.error(f"Failed to download file: {e}")
